extraenv:
  DEBUG: "true"
bootstrapScript: |
  #!/bin/bash
  if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi
  pip install psycopg2-binary
  pip install Authlib sqlalchemy-trino trino trino[sqlalchemy]
  pip install flask_openid PyJWT
# Superset node configuration
supersetNode:
  replicaCount: 1
  connections:
    # -- Change in case of bringing your own redis and then also set redis.enabled:false
    redis_host: "${redis_host}"
    redis_port: "6379"
    redis_user: "${redis_user}"
    # redis_password: superset
    redis_cache_db: "1"
    redis_celery_db: "0"
    # Or SSL port is usually 6380
    # Update following for using Redis with SSL
    redis_ssl:
      enabled: false
      ssl_cert_reqs: CERT_NONE
    # You need to change below configuration incase bringing own PostgresSQL instance and also set postgresql.enabled:false
    db_host: ${db_host}
    db_port: "5432"
    db_user: ${db_user}
    db_pass: ${db_pass}
    db_name: ${db_name}
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80

  resources:
     limits:
      cpu: 200m
      memory: 256Mi
     requests:
      cpu: 200m
      memory: 256Mi
# Superset Celery worker configuration
supersetWorker:
  replicaCount: 1
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
  command:
    - "/bin/sh"
    - "-c"
    - ". {{ .Values.configMountPath }}/superset_bootstrap.sh; celery --app=superset.tasks.celery_app:app worker"
  # -- If true, forces deployment to reload on each upgrade
  forceReload: true
  # -- Init container
  # @default -- a container waiting for postgres and redis
  initContainers:
    - name: wait-for-postgres-redis
      image: "{{ .Values.initImage.repository }}:{{ .Values.initImage.tag }}"
      imagePullPolicy: "{{ .Values.initImage.pullPolicy }}"
      envFrom:
        - secretRef:
            name: "{{ tpl .Values.envFromSecret . }}"
      command:
        - /bin/sh
        - -c
        - dockerize -wait "tcp://$DB_HOST:$DB_PORT" -wait "tcp://$REDIS_HOST:$REDIS_PORT" -timeout 120s

  resources:
    limits:
      cpu: 2000m
      memory: 5092Mi
    requests:
      cpu: 2000m
      memory: 2048Mi

postgresql:
  enabled: false

configOverrides:
   secret: |
     SECRET_KEY = '${secret_key}'
     RATELIMIT_STORAGE_URI = "redis://{{ .Values.supersetNode.connections.redis_host }}:{{ .Values.supersetNode.connections.redis_port }}/3"
     CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

     import jwt

     def user_info(remote, resp):
         token = resp.get('access_token') or resp.get('id_token')
         if not token:
             return {}
         decoded = jwt.decode(token, options={"verify_signature": False})

         return {
             'username': decoded.get('preferred_username') or decoded.get('sub') or '',
             'first_name': decoded.get('given_name') or '',
             'last_name': decoded.get('family_name') or '',
             'email': decoded.get('email') or '',
         }

     from flask_appbuilder.security.manager import AUTH_OAUTH
     ENABLE_PROXY_FIX = True
     PREFERRED_URL_SCHEME = 'https'
     OAUTH_USER_INFO = user_info

     OAUTH_PROVIDERS = [
        {
            'name': 'keycloak',
            'icon': 'fa-address-card',
            'token_key': 'access_token',
            'remote_app': {
                'client_id': '${clientID}',
                'client_secret': '${clientSecret}',
                'api_base_url': '${oidcIssuerURL}/protocol/openid-connect',
                'access_token_url': '${oidcIssuerURL}/protocol/openid-connect/token',
                'authorize_url': '${oidcIssuerURL}/protocol/openid-connect/auth',
                'client_kwargs': {
                    'scope': 'openid email profile',
                },
                'server_metadata_url': '${oidcIssuerURL}/.well-known/openid-configuration'
            },
        },
     ]

     AUTH_TYPE = AUTH_OAUTH
     AUTH_ROLE_PUBLIC = 'Gamma'
     AUTH_USER_REGISTRATION = True
     AUTH_USER_REGISTRATION_ROLE = "Gamma"
     AUTH_ROLES_SYNC_AT_LOGIN = True

     AUTH_ROLES_MAPPING = {
     "superset_admin": ["Admin"],
     "superset_editeur" : ["Alpha"],
     "superset_lecteur" : ["Gamma"]
     }
     

redis:
 enabled: false
runAsUser: 1000


## Création d'un compte admin, mais plus besoin car oidc est utilisé
init:
  # Configure resources
  # Warning: fab command consumes a lot of ram and can
  # cause the process to be killed due to OOM if it exceeds limit
  # Make sure you are giving a strong password for the admin user creation( else make sure you are changing after setup)
  # Also change the admin email to your own custom email.
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 512Mi
  # -- Command
  # @default -- a `superset_init.sh` command
  command:
    - "/bin/sh"
    - "-c"
    - ". {{ .Values.configMountPath }}/superset_bootstrap.sh; . {{ .Values.configMountPath }}/superset_init.sh"
  enabled: true
  jobAnnotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": "before-hook-creation"
  loadExamples: false
  createAdmin: false
  adminUser:
    username: admin
    firstname: Superset
    lastname: Admin
    email: admin@superset.com
    password: admin
  # -- List of initContainers
  # @default -- a container waiting for postgres
  initContainers:
    - name: wait-for-postgres
      image: "{{ .Values.initImage.repository }}:{{ .Values.initImage.tag }}"
      imagePullPolicy: "{{ .Values.initImage.pullPolicy }}"
      envFrom:
        - secretRef:
            name: "{{ tpl .Values.envFromSecret . }}"
      command:
        - /bin/sh
        - -c
        - dockerize -wait "tcp://$DB_HOST:$DB_PORT" -timeout 120s
  # -- A Superset init script
  # @default -- a script to create admin user and initialize roles
  initscript: |-
    #!/bin/sh
    set -eu
    echo "Upgrading DB schema..."
    superset db upgrade
    echo "Initializing roles..."
    superset init
    
    if [ -f "{{ .Values.extraConfigMountPath }}/import_datasources.yaml" ]; then
      echo "Importing database connections.... "
      superset import_datasources -p {{ .Values.extraConfigMountPath }}/import_datasources.yaml
    fi

extraConfigMountPath: /app/configs
extraConfigs:
  import_datasources.yaml: |
    databases:
      - database_name: trino
        sqlalchemy_uri: trino://trino:${trino_password}@${trino_url}/iceberg
        allow_file_upload: true
        allow_ctas: true
        allow_cvas: true
        extra: "{}"
        tables: []